### PR TITLE
Added methods to manipulate json + fix license type

### PR DESCRIPTION
**Pull request by lulco**
I would like to use these methods here https://github.com/rectorphp/rector/pull/5074

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Hi, the contribution looks good!

But this is only split repository (read-only). The main Symplify repository for all packages is here: https://github.com/symplify/symplify

Could you move it there please?

**Comment by lulco** [comment]
ouch :)) ok, I will move it

**Comment by TomasVotruba** [comment]
Thank you. I'm really sorry about this, it's only natural.

It happens once a month, because GitHub does not have an option to disable pull-requests :(

I'll look for option to improve this, there might be some GitHub Action that might simulate this feature: https://stackoverflow.com/questions/27957454/how-to-disable-pull-requests-in-github

**Comment by lulco** [comment]
No problem, my bad. I didn't read the whole readme. It's moved https://github.com/symplify/symplify/pull/2753

**Comment by TomasVotruba** [comment]
> No problem, my bad. I didn't read the whole readme.

No, it's not. I don't read any README before sending a PR. It's always bad UX :)

This might help next time: https://github.com/symplify/symplify/pull/2754


<br>

This is how it looks in practise: https://github.com/symplify/composer-json-manipulator/pull/3

Any tips to improve?

**Comment by lulco** [comment]
The best would be to create PR in target repository :D but I don't know it is even possible. I am not familiar with these actions for now.

**Comment by TomasVotruba** [comment]
Wow, that would be really cool :D 

I mean it's technically possible and I have an idea how to make work. But it can be only create in my name, as the PR GitHub Api needs access token. The author could not modify it :/

**Comment by lulco** [comment]
For me it would be no problem, you can create PR in your name and add comment here that it was created (with link?) - and if they want to has their own name on PR, they could create new one.

**Comment by TomasVotruba** [comment]
In almost everycase extra work is needed, so duplicated PR does not make sense as it will be always closed.

**Comment by lulco** [comment]
I was just thinking loudly O:-)

**Pull request closed without merging**
